### ISSUE TITLE
unable to configure in Azure Databricks. we tried for AWS and working fine but in Azure databricks it is giving below error

### ISSUE THREAD

**Issue by sdubbakagoud** [databrickslabs/overwatch#1168] opened 2024-03-19 16:32 UTC
**Sensitive Content Alert**

**Overwatch Version**
Latest

**Describe the bug**
AzureException: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. Caused by: StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Mahalakshmi1305** [comment] 2024-03-20 06:33
Hi @sdubbakagoud 

Have you added the Spark configuration to your cluster? If not, please check the attached documentation and add those commands to the Spark config with your credentials. 

<img width="773" alt="image" src="https://github.com/databrickslabs/overwatch/assets/146411068/b1af8ae2-63ae-4af9-8ab7-c297687c1a64">

https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config

Regards,
Mahalakshmi

**Comment by sdubbakagoud** [comment] 2024-03-20 07:42
Hi mahalakshmi,

I have added SAS token configuration in the spark. will that not work? i am able to read & write to the container .

**Comment by Mahalakshmi1305** [comment] 2024-03-20 08:27
Hi @sdubbakagoud 

Please schedule a call for review. I am from the IST timezone and available from 11 a.m. to 9 p.m.

Regards,
Mahalakshmi

**Comment by sdubbakagoud** [comment] 2024-03-20 09:29
thanks. sent you the invite

**Comment by Mahalakshmi1305** [comment] 2024-03-20 10:54
To test whether the event hub messages are flowing or not.

```val EHSECRETSCOPE = "secret_scope"
val EHCONNSTRINGKEYNAME = "eh_connection_string"
val EHNAME = "event_hub_name" 

val connectionString = ConnectionStringBuilder(dbutils.secrets.get(EHSECRETSCOPE, EHCONNSTRINGKEYNAME))
  .setEventHubName(EHNAME)
  .build

val ehConf = EventHubsConf(connectionString)
  .setMaxEventsPerTrigger(100)
  .setStartingPosition(EventPosition.fromStartOfStream)

val rawEHDF = spark.readStream
  .format("eventhubs")
  .options(ehConf.toMap)
  .load()
  .withColumn("deserializedBody", 'body.cast("string"))

display(rawEHDF)```

**Comment by Mahalakshmi1305** [comment] 2024-03-29 15:21
Hi @sdubbakagoud,

We are closing the ticket since it is not an overwatch issue, as confirmed in the last meeting.

Thanks,
Mahalakshmi

**Closed** 2024-03-29 15:22 UTC
Labels: user_question
