### ISSUE TITLE
Have the same org_id on multiple workspaces

### ISSUE THREAD

**Issue by dayrosem** [databrickslabs/overwatch#320] opened 2022-03-09 20:39 UTC
We have two Overwatch jobs for two different workspaces both running in the same workspace. Their organization IDs are different in the configuration but after running Overwatch, they appear the same in the tables causing merge issues. 

```
FAILED --> ERROR: Gold_jobRunCostPotentialFact FAILED --> Cannot perform Merge as multiple source rows matched and attempted to modify the same target row in the Delta table in possibly conflicting ways. By SQL semantics of Merge, when multiple source rows match on the same target row, the result may be ambiguous as it is unclear which source row should be used to update or delete the matching target row. You can preprocess the source table to eliminate the possibility of multiple matches. Ple...
```

Initial thought is this section of code in the **initializer.scala (line 504 to 516)** could be causing an issue as `dbutils.notebook.getContext.tags("orgId")` as it captures the organization ID which would be the workspace that the job is running in. Since both jobs are running in the same workspace the same ID is captured at this time.   

```
def getOrgId: String = {
    if (dbutils.notebook.getContext.tags("orgId") == "0") {
      dbutils.notebook.getContext.apiUrl.get.split("\\.")(0).split("/").last
    } else dbutils.notebook.getContext.tags("orgId")
  }

  private def initConfigState(debugFlag: Boolean): Config = {
    logger.log(Level.INFO, "Initializing Config")
    val config = new Config()
    val orgId = if (config.isLocalTesting) System.getenv("ORGID") else {
      getOrgId
    }
    config.setOrganizationId(orgId)
```

This issue appears to be related to the open issue request **Multi-Workspace deploy from single workspace #270** and may have impact to other areas of code base, but unsure.

**Comment by mohanbaabu1996** [comment] 2022-03-11 04:57
Hello, @dayrosem  I'm closing this ticket and inviting you to engage with me to resolve this issue.
The problem is that not to deploy two or more instances of Overwatch from the same workspace even though it have a distinct org ids and database names.

**Closed by mohanbaabu1996** 2022-03-11 04:57 UTC
Labels: user_question
