### ISSUE TITLE
In multi workspace deployment, using v0.7.1, cluster_events_bronze table gets incorrect data

### ISSUE THREAD

**Issue by vos139** [databrickslabs/overwatch#710] opened 2023-01-23 17:01 UTC
cluster_events_bronze only shows details of clusters which are running in workspace where job is running. Its not showing details of clusters from other workspace

**Comment by Neha-vs123** [comment] 2023-01-24 08:11
Hi @vos139 ,

Please share the [config csv](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/configuration/#building-your-config) file that's been uploaded into your workspace for deployment.

**Comment by vos139** [comment] 2023-01-24 15:58
@Neha-vs123  Attached is config file. I have replaced workspace id and url with dummy values
[Config.csv](https://github.com/databrickslabs/overwatch/files/10491753/Config.csv)

Table cluster_events_bronze only gets values from Prod-Shared-Overwatch-Databricks. 

Overwatch job is running on Prod-Shared-Overwatch-Databricks

**Comment by Neha-vs123** [comment] 2023-01-30 16:24
@vos139 We need to get on a call for troubleshooting. We are from the IST time zone. 
Please let me know your time zone and availability to set up a call.

I am available between 8 am and 11 am EST (if you are from the EST), from Monday to Thursday.
This is my mail id - neha.vs@databricks.com

**Comment by Neha-vs123** [comment] 2023-02-03 16:36
@vos139, I've sent a meeting invite for Wednesday.

**Comment by Neha-vs123** [comment] 2023-02-09 07:34
@vos139 , Was the jobrun successful? Please send the pipeline report.

**Comment by Neha-vs123** [comment] 2023-02-15 08:43
@vos139 , Closing this ticket as the issue is resolved.

**Closed by Neha-vs123** 2023-02-15 08:43 UTC
Labels: user_question
