### ISSUE TITLE
FAILED: 1004-Bronze_AuditLogs Module: API CALL Failed

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1043] opened 2023-09-13 17:48 UTC
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets,  

**Overwatch Version**
com.databricks.labs:overwatch_2.12:0.7.2.0.2 (Maven)

**Describe the bug**
 
I've encountered an error in the Overwatch job, causing its duration to be unexpectedly reduced to 13 minutes, when it should typically last for 3 hours.

**Screenshots**

FAILED: 1004-Bronze_AuditLogs Module: API CALL Failed

Can't extract value from parsedBody#1996: need struct type but got void
org.apache.spark.sql.AnalysisException: Can't extract value from parsedBody#1996: need struct type but got void
	at org.apache.spark.sql.errors.QueryCompilationErrors$.dataTypeUnsupportedByExtractValueError(QueryCompilationErrors.scala:779)
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:89)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.$anonfun$resolve$1(package.scala:362)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.resolve(package.scala:361)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveChildren(LogicalPlan.scala:115)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$resolveExpressionByPlanChildren$1(Analyzer.scala:2532)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$resolveExpression$2(Analyzer.scala:2462)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:60)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.innerResolve$1(Analyzer.scala:2469)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$resolveExpression$7(Analyzer.scala:2482)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1241)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1240)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:607)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.innerResolve$1(Analyzer.scala:2482)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$resolveExpression$7(Analyzer.scala:2482)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1241)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1240)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:607)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.innerResolve$1(Analyzer.scala:2482)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.resolveExpression(Analyzer.scala:2487)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.resolveExpressionByPlanChildren(Analyzer.scala:2538)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$16.$anonfun$applyOrElse$89(Analyzer.scala:2251)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:202)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:168)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:202)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:213)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:218)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:218)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:223)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:433)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:223)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$16.applyOrElse(Analyzer.scala:2251)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$16.applyOrElse(Analyzer.scala:2078)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:134)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:130)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:2078)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:2059)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$3(RuleExecutor.scala:216)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:216)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:205)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:205)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:304)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:297)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:199)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:297)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:225)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:184)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:142)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:184)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:277)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:331)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:276)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:128)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:300)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:265)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:265)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:129)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:126)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:118)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:93)
	at org.apache.spark.sql.Dataset.withPlan(Dataset.scala:3985)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1554)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.getAuditLogsDF(BronzeTransforms.scala:344)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.getAuditLogsDF$(BronzeTransforms.scala:327)
	at com.databricks.labs.overwatch.pipeline.Bronze.getAuditLogsDF(Bronze.scala:8)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$appendAuditLogsProcess$1(Bronze.scala:142)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:375)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:293)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:288)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:329)
	at com.databricks.labs.overwatch.BatchRunner$.main(BatchRunner.scala:58)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command--1:1)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw$$iw$$iw$$iw$$iw.<init>(command--1:43)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw$$iw$$iw$$iw.<init>(command--1:45)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw$$iw$$iw.<init>(command--1:47)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw$$iw.<init>(command--1:49)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$$iw.<init>(command--1:51)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read.<init>(command--1:53)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$.<init>(command--1:57)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$read$.<clinit>(command--1)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$eval$.$print$lzycompute(<notebook>:7)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$eval$.$print(<notebook>:6)
	at $line8a5b6b4c79864c278a1a7c0ed62fce0d25.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1013)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:966)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$13(DriverLocal.scala:644)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:59)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:59)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:621)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:750)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by hazearias** [comment] 2023-09-13 17:49
The issue was found it on this link https://adb-8755884253711570.10.azuredatabricks.net/?o=8755884253711570#job/44724029/run/2375422465

**Comment by gueniai** [comment] 2023-09-13 17:49
Hi @hazearias can you please try running with the latest version, 0.7.2.1? Just swap the jar, no upgrade needed.

**Comment by hazearias** [comment] 2023-09-13 18:51
I did that and still have the same result

**Comment by mohanbaabu1996** [comment] 2023-09-14 06:40
Hi @hazearias ,

It seems like event hubs is not streaming the messages. Have you created the SAS connection string from event hub and did you also configured your diagnostic settings ?
What's the primordial date configured in the input ?

**Comment by hazearias** [comment] 2023-09-14 16:09
It was working normally on tuesday and I do not think something was configured differently between tuesday when was working normally and today 

\"primordialDateString\":\"2021-12-16\"
They are using legacy overwatch

**Comment by mohanbaabu1996** [comment] 2023-09-17 07:50
Hi @hazearias ,

Can you please run the below code using scala and test the event hub connectivity.
Kindly remember that event hub library is installed

`com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21`

```
val SECRETSCOPE = ""
val EHCONNSTRINGKEYNAME = ""
val EHNAME = ""

import org.apache.spark.eventhubs.{ConnectionStringBuilder, EventHubsConf, EventPosition}
val connectionString = ConnectionStringBuilder(dbutils.secrets.get(SECRETSCOPE, EHCONNSTRINGKEYNAME))
  .setEventHubName(EHNAME)
  .build

val ehConf = EventHubsConf(connectionString)
  .setMaxEventsPerTrigger(100)
  .setStartingPosition(EventPosition.fromStartOfStream)

val rawEHDF = spark.readStream
  .format("eventhubs")
  .options(ehConf.toMap)
  .load()
  .withColumn("deserializedBody", 'body.cast("string"))

display(rawEHDF)
```

**Comment by hazearias** [comment] 2023-09-19 19:25
Hi Mohan!

I run this command, but had a duration longer than 24 hours and still nothing

**Comment by mohanbaabu1996** [comment] 2023-09-20 05:40
Hi @hazearias ,

Are you able to get the streaming output ? If not please check the event hub configurations or check with Microsoft team.

**Comment by mohanbaabu1996** [comment] 2023-09-25 06:24
Hi @hazearias,

I hope the issue is fixed by running the upgrdation script.
Please let us know if you've any issues.

Thanks,
Mohan Baabu

**Closed by mohanbaabu1996** 2023-09-25 06:24 UTC
Labels: user_question

**Comment by hazearias** [comment] 2023-09-26 19:55
Hello Mohan, Guenia,

The issue is still on going status
